### ISSUE TITLE
How can I use this in a project?

### ISSUE THREAD

**Issue by nolanjannotta** [rroels/rust-it8951#1]
Hello, I'm fairly new to this. 
I would like to use this library on a raspberry pi pico w, would that work? If you have any guidance on how to get this working, that would be amazing. Also where is the code in the repo?

Thanks!

**Comment by rroels** [comment]
@nolanjannotta 

Sorry, the project was never finished and has been abandoned. I am keeping this repository online just in case the references or buspirate tutorial can be of use to someone who wants to implement something similar.

**Comment by nolanjannotta** [comment]
gotcha, thanks for getting back. do you know of any other resources i could by chance?
